version: 0.2

env:
  variables:
    IMAGE_PREFIX: 'risken-gateway'
  parameter-store:
    DOCKER_USER: '/build/DOCKER_USER'
    DOCKER_TOKEN: '/build/DOCKER_TOKEN'
    VITE_RUM_ID: '/build/datadog/VITE_RUM_ID'
    VITE_RUM_TOKEN: '/build/datadog/VITE_RUM_TOKEN'
    VITE_STATIC_LINK: '/build/web/VITE_STATIC_LINK'
    VITE_GENERATIVE_AI_ENABLED: '/build/web/VITE_GENERATIVE_AI_ENABLED'

phases:
  pre_build:
    commands:
      - echo Setting environment variables
      - BUILD_OPT="--no-cache --pull"
      - TAG=$(git rev-parse --short HEAD)_${OS}_${ARCH}
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
      - REGISTRY=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com

      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${REGISTRY}

      - |
        #!/bin/bash
        if [[ -n "${DOCKER_USER}" ]] && [[ -n "${DOCKER_TOKEN}" ]]; then
          echo 'Logging in to Docker Hub...'
          echo "$DOCKER_TOKEN" | docker login -u $DOCKER_USER --password-stdin
        fi
  build:
    commands:
      - echo Build web started on `date`
      - echo "VITE_RUM_ID=${VITE_RUM_ID}" > .env.prd
      - echo "VITE_RUM_TOKEN=${VITE_RUM_TOKEN}" >> .env.prd
      - echo "VITE_STATIC_LINK='${VITE_STATIC_LINK}'" >> .env.prd
      - echo "VITE_GENERATIVE_AI_ENABLED='${VITE_GENERATIVE_AI_ENABLED}'" >> .env.prd

      - echo Building the Docker images...
      - make build-ci -j BUILD_OPT="${BUILD_OPT}" IMAGE_PREFIX=${IMAGE_PREFIX} IMAGE_TAG=${TAG} IMAGE_REGISTRY=${REGISTRY}

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - make push-image -j IMAGE_PREFIX=${IMAGE_PREFIX} IMAGE_TAG=${TAG} IMAGE_REGISTRY=${REGISTRY}
