version: 0.2

env:
  variables:
    IMAGE: "gateway/web"

phases:
  install:
    runtime-versions:
      node: lts-alpine

  pre_build:
    commands:
      - echo "Setting environment variables"
      - BUILD_OPT="--no-cache --pull"

      - echo "linter"
      - cd ${CODEBUILD_SRC_DIR} && yarn install && yarn lint

  build:
    commands:
      - echo "Build web started on `date`"
      - cd ${CODEBUILD_SRC_DIR} && docker build ${BUILD_OPT} -t ${IMAGE}:test .
