version: 0.2

env:
  variables:
    IMAGE_PREFIX: "risken-gateway"

phases:
  install:
    runtime-versions:
      nodejs: 12

  pre_build:
    commands:
      - echo "Setting environment variables"
      - BUILD_OPT="--no-cache --pull"
      - TAG=$(git rev-parse --short HEAD)_${OS}_${ARCH}
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
      - REGISTRY=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com

      - echo "linter"
      - make install && make test

  build:
    commands:
      - echo "Build web started on `date`"
      - make build-ci -j BUILD_OPT="${BUILD_OPT}" IMAGE_PREFIX=${IMAGE_PREFIX} IMAGE_TAG=${TAG} IMAGE_REGISTRY=${REGISTRY}
