export const INVITATION_STATUS = {
    PENDING: 'PENDING',
    ACCEPTED: 'ACCEPTED',
    REJECTED: 'REJECTED',
    UNKNOWN: 'UNKNOWN',
  }
  
Object.freeze(INVITATION_STATUS)

export default INVITATION_STATUS